import addContact from './add-contact.png'
import bin from './bin.png'
import boxes from './boxes.png'
import check from './check.png'
import edit from './edit.png'
import grid from './grid.png'
import lines from './lines.png'
import lock from './lock.png'
import mail from './mail.png'
import search from './search.png'
import share from './share.png'
import sidebar from './sidebar.png'
import sidebarRight from './sidebar-right.png'
import textFont from './text-font.png'

export {addContact, boxes, check, edit , grid, bin, lock, mail, search, share, sidebar, sidebarRight, lines, textFont}